### ISSUE TITLE
Gatling Tank Teleports (On Top of a technical) In the Same Instant when it's spawned from WF in the place of Dead Burned RPG that dies and Enters a Technical At the Same time

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#1196] opened 2022-09-14 00:55 UTC
[Gatling Teleport](https://youtu.be/asZ_WxBb_YY?t=110)

Needs Testing

**Comment by commy2** [comment] 2022-09-14 05:33
LOL

**Comment by xezon** [comment] 2022-09-14 10:07
Duplicate of TheSuperHackers/GeneralsGameCode#130

**Closed as not planned by xezon** 2022-09-14 10:07 UTC
Labels: Duplicate
