### ISSUE TITLE
Add or Tweak the model for the Unused Tech Repair Pad Building for the mappers to use in their maps (RANKed and nonRANKed)

### ISSUE THREAD

**Issue by MTKing4** [TheSuperHackers/GeneralsGamePatch#290] opened 2021-09-11 07:52 UTC
Originally suggested by General Camo to use the Shockwave Model
> Do you know of any maps that use the Repair Pad ATM. It may be an option to use the model from Shockwave, possibly with modifications
https://www.moddb.com/mods/cc-shockwave/images/tech-repair-pad
![repairpad1](https://user-images.githubusercontent.com/83613147/132940418-7cdfac51-4463-40f5-abef-8e25c1728bf4.gif)

Next Suggestion by Zeke
> We currently do have a hexagon SDZ model that we got from TipaIvan before, if ever, that model can be cleaned up and repurposed for this
https://www.moddb.com/mods/cc-generals-revolution/images/supply-drop-zone
![repairpad2](https://user-images.githubusercontent.com/83613147/132940427-1df44e98-6c88-4a85-84a7-89ef9e3dfc4f.jpg)

this is how it looks like in the current version of the game (bottom left is Repair Pad, Top right is Supply Drop Zone)

![repairpad3](https://user-images.githubusercontent.com/83613147/132940449-fdde8e4c-fc51-4ba3-af4d-af9a76e2dbb4.jpg)

as you can see it looks strikingly similar to the drop zone which will confuse the players hence mappers don't use it that often

+ it's functional with its current state
+ Would be great to have a model that represents it the best and get it into maps
+ it can add more diversity and dynamic to how maps will be played
+ it will still be optional and it will be up to the mappers to decide to add it into their maps or not
+ if a map has it implemented already with the current model and you play it with the game version that has the updated model, it will load the newer model anyway (need further investigation on that)

**Comment by xezon** [comment] 2021-09-11 07:57
This is a duplicate of #93
I copy your post and close this one.

**Closed as duplicate by xezon** 2021-09-11 07:57 UTC
Labels: Duplicate
