### ISSUE TITLE
Vanilla Battlemaster China is overpriced for its utility

### ISSUE THREAD

**Issue by bolchevique30** [TheSuperHackers/GeneralsGamePatch#2066] opened 2023-07-08 04:20 UTC
Battlemaster de china vainilla  es excesivamente caro,disminuir su coste a 750 o 700

Esta unidad es demasiado cara para su mediocre desempeño y puesto que no posee la veterania del tank ni las mejoras de antemano del nuke,suguiero este cambio para que tenga cierta utilidad ya que actualmente no ofrece casi ninguna utilidad antes de las mejoras en silo que son bastante caras asi como tambien muy tardias teniendo ya el Overloard tank como mucha mejor opcion.

**Comment by commy2** [comment] 2023-07-08 05:14
machine translation:

Vanilla Battlemaster is overpriced,lower its cost to 750 or 700.

This unit is too expensive for its mediocre performance and since it does not have the tank's veterancy nor the nuke's beforehand upgrades, I suggest this change to give it some utility since it currently offers almost no utility before the silo upgrades which are quite expensive as well as very late having the Overloard tank as a much better option.

Lo he traducido para que otros puedan debatir: https://www.deepl.com/

**Comment by commy2** [comment] 2023-07-08 05:27
I personally do not think the unit is too expensive. People buy Gatling tanks, Dragon tanks and Outposts, $800 isn't too much.

The issues with the 1.04 vChina Battlemaster are:

- extremely slow (25 speed, vs 30 of Crusader/Paladin/Dragon/Marauder and 40 of Gattling/Outpost/ECM/Scorpion/Quad) -> Dragons just run around you, no synergy with the rest of your army
- grants tank exp to enemy when killed (100 @ vet0&1 vs 50 of Quad, Gatling, Dragon, Humvee etc. etc.) -> enemy punishes you with genpowers
- generally long build time of China vehicles due to the 4 seconds per vehicle door opening animation time of the China War Factory -> you need 2 WF builds if you want to keep up 
- Some underwhelming upgrades like Nuclear Tanks and Depleted Uranium Shells that do too little for how late they come -> no late game potential and upgrades remain ignored

**Comment by xezon** [comment] 2023-07-08 05:40
3 of these 4 points have been addressed. Battlemaster now drives faster, gives less XP on kill, China Warfactory has quicker door time.

**Comment by xezon** [comment] 2023-07-08 05:42
We already determined that current improvements are sufficient. Therefore closing as duplicate of #819.

**Closed as not planned by xezon** 2023-07-08 05:42 UTC
Labels: Duplicate

**Comment by bolchevique30** [comment] 2023-07-09 02:36
@xezon quiere decir que los 3 cambios serian:

> Se han abordado 3 de estos 4 puntos. Battlemaster ahora conduce más rápido, da menos XP al matar, China Warfactory tiene un tiempo de puerta más rápido.

@xezon estoy de acuerdo con los 3 puntos conseguidos,aunque es incomodo ver que scorpions con cohete ganan valiendo 150 o 200 menos,podria tocarse ligeramente su precio tipo 750 para hacerle mas atractivo ya que poco se ve o como dijo el compa mas arriba,dar alguna mejora ya que las de silo nuclear son en demasia tardes

**Comment by commy2** [comment] 2023-07-09 04:39
Battlemaster does 30 dmg/sec and 38 dmg/sec (Nationalism or Horde) and 47 dmg/sec (Nationalism and Horde), while Scorpion does 20 dmg/sec (gun) + 7 dmg/sec (rocket). The Battlemaster also has 400 hp vs 370 of the Scorpion.

Scorpion has 40 speed, while Battlemaster has only 25 and 30 with Nuclear tanks. In patch the Battlemaster will have 30 speed and 40 speed with Nuclear tanks.

Scorpion grants 60 xp when killed, while Battlemaster grants 100 xp. In patch, Battlemaster will grant 70 xp.

It is a better vehicle in raw stats, except for the abysmal speed and veterancy bounty. Both addressed already. Making it cheaper on top is not necessary in my opinion.

**Comment by bolchevique30** [comment] 2023-07-09 04:55
> Battlemaster hace 30 dmg/seg y 38 dmg/seg (Nacionalismo u Horda) y 47 dmg/seg (Nacionalismo y Horda), mientras que Scorpion hace 20 dmg/seg (arma) + 7 dmg/seg (cohete). El Battlemaster también tiene 400 CV frente a los 370 del Scorpion.
> 
> Scorpion tiene 40 de velocidad, mientras que Battlemaster tiene solo 25 y 30 con tanques Nuclear. En el parche, el Battlemaster tendrá velocidad 30 y velocidad 40 con tanques nucleares.
> 
> Scorpion otorga 60 xp cuando muere, mientras que Battlemaster otorga 100 xp. En el parche, Battlemaster otorgará 70 xp.
> 
> Es un vehículo mejor en estadísticas brutas, excepto por la velocidad abismal y la recompensa por la veteranía. Ambos ya se abordaroMuchas gracias por la respuestan. Hacerlo más barato encima no es necesario en mi opinión.

Thank you very much for the reply,only 7 damage per rocket?what a curiosity

**Comment by xezon** [comment] 2023-07-09 05:00
7 damage per second (DPS), because of its long reload.

**Comment by commy2** [comment] 2023-07-09 05:01
100 dmg per rocket. Rocket reload is 15 seconds. 100/15=7 dmg/sec

Granted, the Scorpion Rocket does EXPLOSION type damage, which is more valuable than ARMOR_PIERCING and makes it useful against infantry. Although that doesn't help in tank vs tank battles.
