### ISSUE TITLE
Buggies running in range of firebase/patriot

### ISSUE THREAD

**Issue by Madrageeeeee** [TheSuperHackers/GeneralsGamePatch#480] opened 2021-10-05 12:13 UTC
Unsure what causes this. Often buggies will run into firing range of a firebase or patriot missile even though they actually CAN outrange them. Makes for annoying unnecessary micro and unpredictable behavior. 

Dont think it is necessarily caused by the terrain. Even on flat terrain it happens.

here you can see an example of how Boycah needs to stop and attack, stop and attack in order to prevent his buggies from running into the patriot missile. 

https://youtu.be/OVxNo2izs7g?t=4730

**Comment by xezon** [comment] 2021-10-05 12:15
Duplicate of
* #52

**Closed as completed** 2021-10-05 12:15 UTC
Labels: Duplicate

**Comment by Madrageeeeee** [comment] 2021-10-05 12:25
oki, soz
