### ISSUE TITLE
The preparation time of the vanilla china nuclear silo is excessively slow (6 minutes).

### ISSUE THREAD

**Issue by bolchevique30** [TheSuperHackers/GeneralsGamePatch#2077] opened 2023-07-09 02:50 UTC
Vanilla China according to data from several tournaments is the worst faction, the percentages do not lie:
2014-2015 tournaments: 25% / 75%win/loss rate.
https://www.gamereplays.org/community/index.php?showtopic=965214

Therefore I suggest this change to increase their power and also the utility of producing their SW.

+reduce the time of the super weapon to 5 minutes (-1 minute)

PS: I will upload little by little more changes regarding chinaV not to summarize all the changes that I see optimal for this faction so mediocre in tournaments.

**Comment by MTKing4** [comment] 2023-07-09 03:18
Please post your report in English, not everyone here knows Spanish

Use this: https://www.deepl.com/

**Comment by bolchevique30** [comment] 2023-07-09 03:44
corrected :)

**Comment by MTKing4** [comment] 2023-07-09 04:06
Thank you

**Comment by MTKing4** [comment] 2023-07-09 04:10
Now regarding the Nuclear Missile, we've already increased its damage radius and made it do its damage overtime rather than doing all damage on first hit, meaning GLA holes now die to nukes, i think that buff is enough already and time reduction does not feel necessary right now

**Comment by bolchevique30** [comment] 2023-07-09 04:13
interesting, you talk as if it was done but where can I see the change?
I understand that all this is to account for a new version, I play 1.4 and I see china v very badly

**Comment by xezon** [comment] 2023-07-09 04:17
Current Nuke Missile improvements are

* #410
* #871
* #880
* #1490

**Comment by xezon** [comment] 2023-07-09 04:19
Duplicate of #853

**Closed as not planned by xezon** 2023-07-09 04:19 UTC
Labels: Duplicate

**Comment by bolchevique30** [comment] 2023-07-09 04:21
Thank you very much for updating me, you are geniuses.
One question, where can I see these changes? Or will it be in a future version?

**Comment by xezon** [comment] 2023-07-09 04:27
There will be a release in the future.

Right now the way to test this is to download or clone this repository and use Patch104pZH/Scripts/BuildInstallRunWithGui.bat to build and run the project. You do need an original clean install of Generals Zero Hour retail.
