### ISSUE TITLE
GLA Fake/Real buildings cannot have same hotkey

### ISSUE THREAD

**Issue by ReLaX82** [TheSuperHackers/GeneralsGamePatch#908] opened 2022-08-15 08:37 UTC
I would wish to number a fake-barracks and to keep that number once upgrade.

Is that possible?

**Comment by commy2** [comment] 2022-08-15 08:46
Requires engine change in ObjectReplaceUpdate module.

**Comment by xezon** [comment] 2022-08-15 08:51
Duplicate of
* TheSuperHackers/GeneralsGameCode#36

**Closed as not planned by xezon** 2022-08-15 08:51 UTC
Labels: Duplicate
