### ISSUE TITLE
Switching between fake and real GLA buildings is laggy

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1133] opened 2022-09-05 19:25 UTC
> This can be helpful in GLAs especially, when i sometimes place a fake barracks/arms dealer, the worker was already talking, i don't get audible feedback, i come back a minute later, i have no arms dealer (a noob i know)

The laggy switch between fake and real buildings is definitely a problem, because the scaffold seems to appear at first but then just disappears? So you scroll away and come back to discover nothing was build, this sucks.

To get around the problem, one has to develop a habit of "pre-switching", which is learned and discovered pretty easy (if you have a brain :P), however sometimes you still may want to switch and build fast.  Or you simply forgot, happens aswell.

_Originally posted by @ImTimK in https://github.com/TheSuperHackers/GeneralsGamePatch/issues/1128#issuecomment-1237406872_

**Comment by xezon** [comment] 2022-09-05 19:44
Duplicate of TheSuperHackers/GeneralsGameCode#44

**Closed as not planned by xezon** 2022-09-05 19:44 UTC
Labels: Duplicate
