### ISSUE TITLE
Reduce healing rate of ambulance as Vee/Ambulance Combination can be too hard to stop

### ISSUE THREAD

**Issue by ReLaX82** [TheSuperHackers/GeneralsGamePatch#907] opened 2022-08-15 07:54 UTC
For sure highly controversal change, but I think to stop this combination it would be possible to reduce the healing "capacity" on Vees a little.

This can be done also by reducing the speed of the ambulance or/and healing rate.

Any other thoughts?

**Comment by xezon** [comment] 2022-08-15 08:00
I am skeptical about touching Humvees. Weaking Ambulance will hurt noob and semi players. It is already not so easy to micro USA Humvees if opponent puts decent pressure, or if latency is high.

Despite, this seems to be duplicate of
* #640

**Closed as not planned** 2022-08-15 08:52 UTC
Labels: Duplicate
